#!/bin/sh
HOST=$1
BASEDIR=$2
NUM=$3

DIR=`dirname $0`
LIBPATH="${DIR}/lib"
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

teamname="ITAndroids"
player="${DIR}/ITAndroids_player"
coach="${DIR}/ITAndroids_coach"
config="player.conf"
config_dir="formations-dt"
coach_config="coach.conf"
team_graphic="--use_team_graphic on --team_graphic_file ${DIR}/team_logo.xpm"
opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"
coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"
coachopt="${coachopt} ${team_graphic}"
cd $BASEDIR
case $NUM in
    1)
    		$player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
    		$player $opt
        ;;
esac
