#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3

player="/home/username/rcss/teams/rc2023/Oxsy/bin/oxsyplayer"
coach="/home/username/rcss/teams/rc2023/Oxsy/bin/oxsycoach"

opt="-server_ip ${HOST}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -goalie
        ;;
    12)
        $coach $opt
        ;;
    *)
        $player $opt
        ;;
esac
