#!/bin/bash
BASEDIR=$HOME/rcss/teams/rc2023/RoboCIn/
unum=1
while [ $unum -le 13 ]; do
  bash /home/username/rcss/teams/rc2023/RoboCIn/start "127.0.0.1" $BASEDIR $unum &
  sleep 0.2
  unum=`expr $unum + 1` 
done
