#!/bin/sh
HOST=$1
BASEDIR=$2
NUM=$3

LIBPATH=/home/username/rcss/teams/rc2023/RoboCIn/lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

teamname="RoboCIn"

player="/home/username/rcss/teams/rc2023/RoboCIn/src/robocin_player"
coach="/home/username/rcss/teams/rc2023/RoboCIn/src/robocin_coach"

config="/home/username/rcss/teams/rc2023/RoboCIn/src/player.conf"
config_dir="/home/username/rcss/teams/rc2023/RoboCIn/src/formations/standard"
coach_config="/home/username/rcss/teams/rc2023/RoboCIn/src/coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"

team_graphic="--use_team_graphic on --team_graphic_file /home/username/rcss/teams/rc2023/RoboCIn/src/team_logo.xpm"
coachopt="${coachopt} ${team_graphic}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
