#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3
DIR=`dirname $0`

LIBPATH="${DIR}/Lib"
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi

teamname="The8"

player="${DIR}/The8_player"
coach="${DIR}/The8_coach"

config="${DIR}/player.conf"
config_dir="${DIR}/Formations"
coach_config="${DIR}/coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
  
