#!/sh

HOST=$1
BASEDIR=$2
NUM=$3

LIBPATH=/home/username/rcss/teams/YuShan2023/data/lib
if [ x"$LIBPATH" != x ]; then
  if [ x"$LD_LIBRARY_PATH" = x ]; then
    LD_LIBRARY_PATH=$LIBPATH
  else
    LD_LIBRARY_PATH=$LIBPATH:$LD_LIBRARY_PATH
  fi
  export LD_LIBRARY_PATH
fi


teamname="YuShan2023"

player="/home/username/rcss/teams/YuShan2023/YuShan2023_Player"
coach="/home/username/rcss/teams/YuShan2023/YuShan2023_Coach"

config="/home/username/rcss/teams/YuShan2023/data/player.conf"
coach_config="/home/username/rcss/teams/YuShan2023/data/coach.conf"
config_dir="/home/username/rcss/teams/YuShan2023/data/formations-dt"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"

coachopt="--coach-config ${coach_config} --use_team_graphic on"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
